### ISSUE TITLE
Create a Global

### ISSUE THREAD

**Issue by MarcoPolo** [MaulingMonkey/jni-bindgen#52]
Global is defined as public in jni-glue, but there doesn't seem to be anything that lets me actually make one.

Maybe a `impl From<Local<Class>> for Global<Class>` would make sense? And an equivalent for `Argument<Class>`?

**Comment by MaulingMonkey** [comment]
From impls to convert between locals and globals probably makes sense, yeah.  This should probably also gain `from_env_object` and `leak` methods like `Local` already has, if only for interoperating with existing C/C++ code that might use global `jobject` s.
