### ISSUE TITLE
Return something from with_env() method

### ISSUE THREAD

**Issue by katyo** [MaulingMonkey/jni-bindgen#56]
I propose to have possibility to return something from inner closure, so the `wrap_env()` method, which defined as:
https://github.com/MaulingMonkey/jni-bindgen/blob/eb0a436b8a957e12afbca9e180cc2623b12bf17d/jni-glue/src/vm.rs#L26
it would be better to define it like below:
```rust
pub fn with_env<F: FnOnce(&Env)->R, R>(&self, callback: F) -> R
```

**Comment by MaulingMonkey** [comment]
I could maybe see this maybe becoming a `Result<R, ???>` at some point in the future, to provide a less automatically panicy API, but this seems good to me for now!
