### ISSUE TITLE
How to create java string from &str

### ISSUE THREAD

**Issue by katyo** [MaulingMonkey/jni-bindgen#58]
This feature is missing or I don't understand little bit.

My quick solution for ascii only looks too dirty:
```rust
pub fn new_string<'env, S: AsRef<str>>(env: &'env Env, string: S) -> Local<'env, java::lang::String> {
    java::lang::String::new_byte_array(
        env,
        Some(&*PrimitiveArray::from(
            env,
            unsafe { transmute::<&[u8], &[i8]>(string.as_ref().as_bytes()) }
        ))
    ).unwrap()
}
```

**Comment by MaulingMonkey** [comment]
String creation needs improvement.  Maybe a `from_str` method in https://github.com/MaulingMonkey/jni-bindgen/blob/master/jni-android-sys/src/extras/strings.rs ?

**Comment by katyo** [comment]
It would be nice
