### ISSUE TITLE
Overhead related to holding reference to env

### ISSUE THREAD

**Issue by katyo** [MaulingMonkey/jni-bindgen#63]
Of course, it allows eliminate env argument for methods calls, but I don't sure that it is so matter.
From the other side, the env is not the property of objects, because it is a runtime thing.
I suspect the memory overhead more matter then little benefits.

**Comment by MaulingMonkey** [comment]
I assume you're talking about the overhead of having `Local<...>` store a reference to `env`?

This is on my list of things to try and fix... possibly with thread local storage of the env, possibly with explicitly passing the env to all function calls.  First I want to make it much easier/faster to build and test bindings - I've been working on [another crate](https://github.com/MaulingMonkey/jerk) to help with this.

One complication:  There can technically be multiple JVMs.  I'd like this to be sound, if slow, with feature flags or similar to opt into a fast path that assumes there's only one, possibly permanent VM.  Even that should be backed up by asserts/aborts to keep things sound.

I'm under the impression that JNI interop is pretty slow anyways, so a little more overhead from this library probably isn't too big a deal, but hopefully I'll eventually get benchmarks that can confirm one way or the other.

**Comment by katyo** [comment]
I mean that I don't sure this is right:
https://github.com/MaulingMonkey/jni-bindgen/blob/91b3eac7821d03279f87d18836b4d3bb0c150bea/jni-glue/src/object_and_env.rs#L5-L8
I think this is harmless to pass env explicitly.

**Comment by MaulingMonkey** [comment]
Closing in favor of https://github.com/MaulingMonkey/jni-bindgen/issues/20 which I've taken the time to flesh out the options of more.

Explicit is definitely an option in single-VM builds.  TLS storage is another option in single-VM builds.  Multi-VM... I'll have to think about.
